// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mummy_42_Intex.Data;

namespace Mummy_42_Intex.Migrations
{
    [DbContext(typeof(ArtifactContext))]
    partial class ArtifactContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("Mummy_42_Intex.Models.Artifacts", b =>
                {
                    b.Property<int>("ArtifactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CurrentLocation")
                        .HasColumnType("TEXT");

                    b.Property<string>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Dimensions")
                        .HasColumnType("TEXT");

                    b.Property<string>("Material")
                        .HasColumnType("TEXT");

                    b.Property<string>("StorageLocation")
                        .HasColumnType("TEXT");

                    b.HasKey("ArtifactId");

                    b.ToTable("Artifacts");

                    b.HasData(
                        new
                        {
                            ArtifactId = 1,
                            CurrentLocation = "Rio",
                            Date = "2022-01-13",
                            Description = "Big and scary",
                            Dimensions = "6 ft",
                            Material = "Spikes",
                            StorageLocation = "Chicago"
                        },
                        new
                        {
                            ArtifactId = 2,
                            CurrentLocation = "Spain",
                            Date = "2022-04-30",
                            Description = "Small and fluffy",
                            Dimensions = "8 in",
                            Material = "Cotton",
                            StorageLocation = "Chicago"
                        },
                        new
                        {
                            ArtifactId = 3,
                            CurrentLocation = "Rio",
                            Date = "2022-01-13",
                            Description = "Big and scary",
                            Dimensions = "6 ft",
                            Material = "Spikes",
                            StorageLocation = "Chicago"
                        },
                        new
                        {
                            ArtifactId = 4,
                            CurrentLocation = "Spain",
                            Date = "2022-04-30",
                            Description = "Small and fluffy",
                            Dimensions = "8 in",
                            Material = "Cotton",
                            StorageLocation = "Chicago"
                        },
                        new
                        {
                            ArtifactId = 5,
                            CurrentLocation = "Rio",
                            Date = "2022-01-13",
                            Description = "Big and scary",
                            Dimensions = "6 ft",
                            Material = "Spikes",
                            StorageLocation = "Chicago"
                        },
                        new
                        {
                            ArtifactId = 6,
                            CurrentLocation = "Spain",
                            Date = "2022-04-30",
                            Description = "Small and fluffy",
                            Dimensions = "8 in",
                            Material = "Cotton",
                            StorageLocation = "Chicago"
                        },
                        new
                        {
                            ArtifactId = 7,
                            CurrentLocation = "Rio",
                            Date = "2022-01-13",
                            Description = "Big and scary",
                            Dimensions = "6 ft",
                            Material = "Spikes",
                            StorageLocation = "Chicago"
                        },
                        new
                        {
                            ArtifactId = 8,
                            CurrentLocation = "Spain",
                            Date = "2022-04-30",
                            Description = "Small and fluffy",
                            Dimensions = "8 in",
                            Material = "Cotton",
                            StorageLocation = "Chicago"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
